from __future__ import annotations

from typing import Any, Protocol

from app.db.models import ChatMessageRecord, ChunkRecord, ConversationRecord, DocumentRecord


class MetadataStore(Protocol):
    async def init(self) -> None: ...

    async def close(self) -> None: ...

    async def list_documents(self) -> list[DocumentRecord]: ...

    async def get_document(self, document_id: str) -> DocumentRecord | None: ...

    async def upsert_document(self, record: DocumentRecord) -> None: ...

    async def delete_document(self, document_id: str) -> None: ...

    async def list_chunks(self, document_id: str | None = None) -> list[ChunkRecord]: ...

    async def replace_document_chunks(self, document_id: str, chunks: list[ChunkRecord]) -> None: ...

    async def create_conversation(self, record: ConversationRecord) -> None: ...

    async def get_conversation(self, conversation_id: str) -> ConversationRecord | None: ...

    async def list_conversations(self, limit: int | None = None) -> list[ConversationRecord]: ...

    async def delete_conversation(self, conversation_id: str) -> None: ...

    async def append_chat(self, message: ChatMessageRecord) -> None: ...

    async def list_chat_history(self, conversation_id: str, limit: int | None = None) -> list[ChatMessageRecord]: ...


class VectorStore(Protocol):
    async def init(self) -> None: ...

    async def close(self) -> None: ...

    async def upsert(self, point_id: str, vector: list[float], payload: dict[str, Any]) -> None: ...

    async def delete_by_document(self, document_id: str) -> None: ...

    async def search(
        self,
        query_vector: list[float],
        limit: int,
        filters: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]: ...
